project:
  type: website
  output-dir: docs

website:
  title: "JH"
  navbar:
    left:
      - href: index.qmd
        text: About
      - text: TidyTuesday
        menu:
          - text: 2024, Week 30, American Idol
            href: tidytuesday/2024_w30/2024_w30.qmd
            
format:
  html:
    theme: bootswatch 
    
editor: visual


